<%include file="trigger_defaults.yml"/>
<%include file="default.yml"/>

job_description: Orchestrates the entire process of validating downstream patch
artifactNumToKeep: 10
numOfJobsToKeep: 10
daysToKeep: 10
githubProject: "https://github.com/dimtruck/workshop_demo"
scm:
  gitURL: "ssh://git@github.com/dimtruck/workshop_demo"
  gitBranch: "<%text>${sha1}</%text>"
  refSpec: "+refs/pull/*:refs/remotes/origin/pr/*"
  extensions:
    cleanbeforecheckout: True
triggers:
  github_pr:
    spec: "H/5 * * * *"
    adminlist: "dimtruck melissa-kam"
    orglist: rackerlabs
    cron: "H/5 * * * *"
    triggerPhrase: recheck
    useGitHubHooks: True
    whitelist: dimtruck
dsl: |
     <%text>
     build(&quot;downstream_unit_tests&quot;, BranchName: params.get("ghprbActualCommit"))
     guard {
       parallel ([
         functional_tests:  { 
           retry ( 3 ) {
             build("downstream_functional_tests", sha1: params.get("ghprbActualCommit"), BranchName: params.get("ghprbActualCommit"))
           }
         },
         performance_tests_1:  { 
           retry ( 3 ) {
             build("downstream_performance_tests", sha1: params.get("ghprbActualCommit"), BranchName: params.get("ghprbActualCommit"))
           }
         }
       ])
     } rescue {
       build( "main_cleanup", sha1: params.get("ghprbActualCommit"), BranchName: params.get("ghprbActualCommit"))
     }
     </%text>