<%include file="trigger_defaults.yml"/>
<%include file="default.yml"/>
job_description: Orchestrates the staging blue node deployment and test
artifactNumToKeep: 10
numOfJobsToKeep: 10
daysToKeep: 10
buildParams:
  - paramName: RELEASE_TAG
    paramValue: ""
    paramDesc:  "Release tag"
    paramType: string
  - paramName: RELEASE_DESCRIPTION
    paramValue: ""
    paramDesc:  "Release description"
    paramType: string
  - paramName: CUT_NEW_RELEASE
    paramValue: "true"
    paramDesc:  "Check if you want to cut a new release (will break if RELEASE TAG already exists)"
    paramType: boolean
  - paramName: RUN_TESTS
    paramValue: "true"
    paramDesc:  "Check if you want to run smoke tests."
    paramType: boolean
dsl: |
      if(params.get("CUT_NEW_RELEASE").equals("true")){
        release_deployer = build(params, "staging_release_deployer")
        out.println release_deployer.result.name
      } 
      guard {
        if(params.get("RUN_TESTS").equals("true")){
          blue_nodes_deployer = build(params, "staging_blue_nodes_deployer_with_tests")
        } else {
          blue_nodes_deployer = build(params, "staging_blue_nodes_deployer")
        }       
        out.println blue_nodes_deployer.result.name 
      } rescue {
        if(blue_nodes_deployer.result.name.equals("FAILURE") || blue_nodes_deployer.result.name.equals("UNSTABLE")){
          build( "staging_blue_nodes_deployer_rescue")
        }
      }